version: '3.3'

services:
  api-jwt-node-service:
    build:
      context: ./
      dockerfile: ./.docker/node/Dockerfile
    container_name: api-jwt-node-container
    restart: always
    ports:
      - $APP_PORT:$APP_PORT
    # For production, comment all volumes
    volumes:
      - ./:/usr/app
    command: npm run dev # For production, change to 'npm start'
    networks:
      - api-jwt-postgres-network

  api-jwt-postgres-service:
    image: postgres
    container_name: api-jwt-postgres-container
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    networks:
      - api-jwt-postgres-network
    environment:
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD

  api-jwt-pgadmin-service:
    image: dpage/pgadmin4
    container_name: api-jwt-pgadmin-container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    ports:
      - 16543:80
    networks:
      - api-jwt-postgres-network
    depends_on:
      - api-jwt-postgres-service

networks:
  api-jwt-postgres-network:
    driver: bridge
