version: '3.3'

services:
  api-jwt-node-service:
    build:
      context: ./
      dockerfile: ./.docker/node/Dockerfile
    container_name: api-jwt-node-container
    restart: always
    ports:
      - $APP_PORT:$APP_PORT
    # For production, comment all volumes
    volumes:
      - ./:/usr/app
    #command: yarn typeorm migration:run # npm run dev # For production, change to 'npm start'
    command: bash -c "
        yarn typeorm migration:run
        && npm run dev"
    networks:
      - api-jwt-postgres-network
    depends_on:
      - api-jwt-postgres-service

  api-jwt-postgres-service:
    image: postgres
    container_name: api-jwt-postgres-container
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    networks:
      - api-jwt-postgres-network
    environment:
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD

networks:
  api-jwt-postgres-network:
    driver: bridge
