version: '3.3'

services:
  react-node-service:
    build:
      context: ./
      dockerfile: ./.docker/node/Dockerfile
    container_name: react-node-container
    restart: always
    ports:
      - $APP_PORT:$APP_PORT
    # For production, comment all volumes
    volumes:
      - ./:/app
    command: npm start # For production, change to 'npm start'